### ISSUE TITLE
Simplify repository structure of jQA core and distributions + Migrate build/release to GH actions

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/Idea-Hub#27]
- provide easy way to clone and build project locally without knowing the dependencies between different repos
- separate between jQA itself and required build infra (checkstyle config, etc.)
- continuous and release builds via GH actions
- provide artifacts for download (especially CLI) including release notes as releases via GH

**Comment by murdos** [comment]
I don't know if it's really related to this ticket, but the other day I tried to compile locally [jqa-core-framework](https://github.com/jQAssistant/jqa-core-framework), and I had to also clone and compile a lot of pair dependencies, including [jqa-asciidoctor-utilities](https://github.com/jQAssistant/jqa-asciidoctor-utilities) and [jqa-checkstyle-config](https://github.com/jQAssistant/jqa-checkstyle-config) that use the same version as jqa-core-framework, but in fact don't change often.
They could easily have a release lifecycle different from jqassistant core distribution.

**Comment by DirkMahler** [comment]
Merging separate repositories into one should be done while preserving the individual histories. A valid approach of how to do this is described [here](https://stackoverflow.com/a/10548919/2912200).

**Comment by DirkMahler** [comment]
@murdos We created a new single repo for the asciidoc/checkstyle/jqa rules: https://github.com/jQAssistant/jqassistant-build/. We added the GH actions for CI and release as well but with the latter we're encountering a permission problem, see https://github.com/jQAssistant/jqassistant-build/actions/runs/9810843046/job/27092333194. Do you have a quick hint available what is missing here?

**Comment by DirkMahler** [comment]
> @murdos We created a new single repo for the asciidoc/checkstyle/jqa rules: https://github.com/jQAssistant/jqassistant-build/. We added the GH actions for CI and release as well but with the latter we're encountering a permission problem, see https://github.com/jQAssistant/jqassistant-build/actions/runs/9810843046/job/27092333194. Do you have a quick hint available what is missing here?

Solved, the SCM URL in the pom.xml was wrong.

**Comment by DirkMahler** [comment]
We're back to one repository now, including GH actions for CI and release - @murdos  thanks for your support!

There are some other things left, e.g. using release drafter and automated publishing of the docs, but this will be handled by separate issues.
